try {
  // code to evaluate

  errorInTry;
} catch (error) {
  // Catch any errors raised in the (try {})

  console.log(error);
} finally {
  //  It will be executed at the and of the try-case

  console.log(`finished code test`);
}
